language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
  - apt-get update 
  - apt-get install cmake libopenmpi-dev python3-dev zlib1g-dev
  - pip install -e .
  - pip install codecov pytest pytest-cov

# command to run tests
script:
  - pytest --cov=./

# command after success
after_success:
  - codecov