language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
  - pip install -e .
  - pip install codecov pytest pytest-cov

# command to run tests
script:
  - pytest --cov=./

# command after success
after_sucess:
  - codecov