language: python
sudo: required
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - sudo apt-get update 
  - sudo apt-get install -y cmake libopenmpi-dev python3-dev zlib1g-dev
  - pip install -e .
  - pip install codecov pytest pytest-cov

# command to run tests
script:
  - pytest --cov=./

# command after success
after_success:
  - codecov